var LanguageStr_Service =
{
    Service_New_Password_Empty : "Please input value in New Password.",
    Service_Confirm_Password_Empty : "Please input value in Confirm New Password.",
    Service_Password_Whitespace : "Can't input whitespace in Password.",
    Service_Password_Not_Same : "New Password and Confirm New Password are not the same.",
    /* SnapShot&Schedule&Backup  2017.01.11 william */   
    Service_SS_Schedule_title : "Scheduled Snapshot - Schedule Setup",
    Service_SS_Schedule_title2 : "Scheduled Snapshot - Snapshot Target Setup",       
    Service_Schedule_DeleteAsk : "Are you sure to delete the snapshot schedule?",
    Service_Schedule_JobsAsk : "Warning: You can only select『One』task,you can not select 『Multiple』tasks!",
    Service_Schedule_RuleAsk : "Warning: You can only select『One』schedule,you can not select 『Multiple』schedule!",    

    Service_BK_Schedule_title : "Scheduled Backup - Schedule Setup",    
    Service_BK_Schedule_title2 : "Scheduled Backup - Backup Target Setup",    

    Service_CheckBackupState0 : "Uninitialization",
    Service_CheckBackupState1 : "Uninitialization",
    Service_CheckBackupState2 : "The backup version is different,You have to initialization Storage",
    Service_CheckBackupState3 : "This iSCSI LUN was used by another HCI Host. Do you want to adopt it?",
    Service_CheckBackupState4 : "",        
    Service_CheckBackupState5 : "Uninitialization",
    Service_BackupDesc_Empty_Warning : "Please enter the value in the description field",
    Service_BackupAsk : "Are you sure to backup VDs?",
    Service_RestoreAsk : "Are you sure to restore VDs?",
    Service_BackupVDDeleteAsk : "Are you sure to delete VDs?",
    VM_BackupType_backup : "Backup",
    VM_BackupType_restorenew : "Create new restore",
    VM_BackupType_restoresame : "Restore Override",    
    VM_BackupType_schedulebackup : "Scheduled backup",
    BackupVD_Rename : "VD's name  already exists,Please rename VD",
    Service_LUN_Connection : "Storage Connection Settings",    
    BackupMgt_Message1 : "Not yet backed up",
    BackupMgt_Message2 : "Not yet restored",
    Backup_FormatAsk : "Are you sure to initialization?",
    CheckBackupLUN_failure : "Connection Failure",
    BackupLUN_disconnect : "Disconnect",
    BackupLUN_OnlineCheck : "Online",
    BackupLUN_OfflineCheck : "Offline",
    Timepicker_btntext_currentText : "Now",
    Timepicker_btntext_closeText : "Done",
    BackupLUN_OfflineMessage_Warning : "Warning !",
    BackupMgt_Bktitle : "Backup",
    Backup_ClearAllAsk : "Are you sure to clear all backup?",    
    Backup_ClearAllComplete : "Clear all backup is completed",
    Backup_SourceVD_Crash : "The VD is damaged and can not be backed up",
    Backup_BKVD_Fail : "Backup failed, please re-backup",
    BackupMgt_AllBK_Capacity : "Backup Capacity : ",
    BackupMgt_Total_Capacity : "Total : ",
    BackupMgt_Avail_Capacity : "Available : ",
    BackupMgt_Used_Capacity : "Used : ",
    BackupMgt_BK_Capacity : "Backup File Size : ",
    BackupMgt_FS_Capacity : "File System Size : ",
    BackupMgt_text_Dot : ".",
    Schedule_Create_Fail : "1. Schedule Name can not 『blank』 or 『repeat』!\n2. Schedule Type and Start Date can not 『blank』!",
    SelectRAID : "Select RAID"
}

