var LanguageStr_Error =
{
    Error_DB : '錯誤 : 資料庫服務無法使用。',
    Error_Authorization : '錯誤 : 認證失敗。',
    Error_PWD_Modify : '錯誤 : 密碼修改失敗。',
    Error_Time_Set : '錯誤 : 時間設定失敗。',
    Error_Time_Update : '錯誤 : 時間更新失敗。',
    Error_Get_IP : "錯誤 : 取得 IP 失敗，因為與伺服器連線失敗。",
    Error_Set_IP : "錯誤 : 設定 IP 失敗，因為與伺服器連線失敗。",
    Error_List_Version : "錯誤 : 取得版本失敗，因為與伺服器連線失敗。",
    Error_Check_Version : "錯誤 : 檢查新版本失敗，因為與伺服器連線失敗。",
    Error_Check_Update : "錯誤 : 更新檢查失敗，因為與伺服器連線失敗。",
    Error_List_log : "錯誤 : 取得日誌失敗，因為與伺服器連線失敗。",
    Error_List_Time : "錯誤 : 取得時間失敗，因為與伺服器連線失敗。",
    Error_Set_Time : "錯誤 : 設定時間失敗，因為與伺服器連線失敗。",
    Error_List_SMB : "錯誤 : 取得 Samba 服務狀態失敗，因為與伺服器連線失敗。",
    Error_Set_SMB : "錯誤 : 設定 Samba 服務狀態失敗，因為與伺服器連線失敗。",
    Error_List_SSH : "錯誤 : 取得 SSH 服務狀態失敗，因為與伺服器連線失敗。",
    Error_Set_SSH : "錯誤 : 設定 SSH 服務狀態失敗，因為與伺服器連線失敗。",
    Error_VM_Status : "錯誤 : 取得 @ 狀態失敗，因為與伺服器連線失敗。",
    Error_List_VM : "錯誤 : 取得 @ 列表失敗，因為與伺服器連線失敗。",
    Error_VM_Shutdown : "錯誤 : @ 關機失敗，因為與伺服器連線失敗。",
    Error_VM_Poweroff : "錯誤 : @ 強制關機失敗，因為與伺服器連線失敗。",
    Error_VM_Poweron : "錯誤 : @ 開機失敗，因為與伺服器連線失敗。",
    Error_VM_Delete : "錯誤 : @ 刪除失敗，因為與伺服器連線失敗。",
    Error_VM_List_Img : "錯誤 : Failed to List existing disk since conneciton timeout.",
    Error_VM_Create : "錯誤 : 建立 @ 失敗，因為與伺服器連線失敗。",
    Error_VM_List_Info : "錯誤 : 取得 @ 資訊失敗，因為與伺服器連線失敗。",
    Error_VM_Delete_Disk : "錯誤 : 刪除 @ 磁碟失敗，因為與伺服器連線失敗。",
    Error_VM_Modify_Properties : "錯誤 : 修改 @ 屬性失敗，因為與伺服器連線失敗。",
    Error_VM_ResetPWD : "錯誤 : 重置 @ 的密碼失敗，因為與伺服器連線失敗。",
    Error_VM_Enable : "錯誤 : 啟用 @ 失敗，因為與伺服器連線失敗。",
    Error_VM_Disable : "錯誤 : 停用 @ 失敗，因為與伺服器連線失敗。",
    Error_VM_List_Task :"錯誤 : 取得 @ 任務列表失敗，因為與伺服器連線失敗。",
    Error_VM_Suspend :"錯誤 : 暫停 @ 失敗，因為與伺服器連線失敗。",
    Error_VM_Clone : "錯誤 : 克隆 @ 失敗，因為與伺服器連線失敗。",
    Error_VM_Delete_Task : "錯誤 : 刪除 @ 任務列表失敗，因為與伺服器連線失敗。",
    Error_SMB_Change_PWD : "錯誤 : 修改密碼失敗，因為與伺服器連線失敗。",
    Error_iSCSI_Discovery : "錯誤 : iSCSI 探索失敗，因為與伺服器連線失敗。",
    Error_iSCSI_Login : "錯誤 : iSCSI 登入失敗，因為與伺服器連線失敗。",
    Error_iSCSI_List : "錯誤 : 取得 iSCSI 列表失敗，因為與伺服器連線失敗。",
    Error_iSCSI_Logout : "錯誤 : iSCSI 登出失敗，因為與伺服器連線失敗。",
    Error_List_Disk : "錯誤 : 取得磁碟列表失敗，因為與伺服器連線失敗。",
    Error_Reset_Disk : "錯誤 :  重置磁碟失敗，因為與伺服器連線失敗。",
    Error_Delete_RAID : "錯誤 : 刪除 RAID 失敗，因為與伺服器連線失敗。",
    Error_Create_RAID : "錯誤 : 建立 RAID 失敗，因為與伺服器連線失敗。",
    Error_Recovery_RAID : "錯誤 : 復原 RAID 失敗，因為與伺服器連線失敗。",
    Error_List_Hostname : "錯誤 : 取得主機名稱失敗，因為與伺服器連線失敗。",
    Error_Set_Hostname : "錯誤 : 設定主機名稱失敗，因為與伺服器連線失敗。",
    Error_List_ExternalIP : "錯誤 : 取得外部 IP 失敗，因為與伺服器連線失敗。",
    Error_Set_ExternalIP : "錯誤 : 設定外部 IP 失敗，因為與伺服器連線失敗。",
    Error_List_Alarm : "錯誤 : 取得蜂鳴器狀態失敗，因為與伺服器連線失敗。",
    Error_Set_Alarm : "錯誤 : 設定蜂鳴器狀態失敗，因為與伺服器連線失敗。",
    Error_VM_Export : "錯誤 : 匯出 @ 失敗，因為與伺服器連線失敗。",
    Error_VM_Import : "錯誤 : 匯入 @ 失敗，因為與伺服器連線失敗。",
    Error_VM_List_Import : "錯誤 : 列出可匯入 @ 失敗，因為與伺服器連線失敗。"
}