var LanguageStr_SharePeriod =
{
	Input_RadioPeriodMode_DateSelect : "請務必選擇日期",
	H4_DescriptionPeriod : "已經過期",
	WDay0 : "星期日",
	WDay1 : "星期一",
	WDay2 : "星期二",
	WDay3 : "星期三",
	WDay4 : "星期四",
	WDay5 : "星期五",
	WDay6 : "星期六",
	WD0 : "日",
	WD1 : "一",
	WD2 : "二",
	WD3 : "三",
	WD4 : "四",
	WD5 : "五",
	WD6 : "六",
	Month01 : "一月",
	Month02 : "二月",
	Month03 : "三月",
	Month04 : "四月",
	Month05 : "五月",
	Month06 : "六月",
	Month07 : "七月",
	Month08 : "八月",
	Month09 : "九月",
	Month10 : "十月",
	Month11 : "十一月",
	Month12 : "十二月",
	PreviosMonth : "上月",
	NextMonth : "次月",
        SelectTime : "選擇時分秒",
        Time : "時間",
	WeekHeader : "週",
	Hour : "時",
	Minute : "分",
	Second : "秒",
        MilliSecond : "毫秒",
        TimeZone : "時區",
        AM : "上午",
        PM : "下午",
	NowTime : "現在時間",
	OK : "確定",
	
	
	AjaxMsg00 : "設定分享期間成功",
	AjaxMsg01 : "設定分享期間錯誤，參數錯誤",
	AjaxMsg02 : "設定分享期間錯誤，Access Key 錯誤",
	AjaxMsg03 : "設定分享期間錯誤，資料庫錯誤",
	AjaxMsg04 : "您沒有變更分享期間",
	AjaxMsg05 : "無法設定今天之前的日期（無效設定）",
	AjaxMsg06 : "設定分享期間錯誤，修改內容錯誤",
	AjaxMsg07 : "設定分享期間錯誤 未知的原因，代碼為：",
	AjaxMsg08 : "刪除分享錯誤，Ajax Error:",
	
	AjaxMsg10 : "刪除帳號分享錯誤，參數錯誤",
	AjaxMsg11 : "刪除帳號分享錯誤，Access Key 錯誤",
	AjaxMsg12 : "刪除帳號分享錯誤，資料庫錯誤",
	AjaxMsg13 : "刪除帳號分享錯誤，建立錯誤",
	AjaxMsg14 : "刪除帳號分享錯誤，未知的原因，代碼為：",
	AjaxMsg15 : "刪除成功",
	AjaxMsg16 : "刪除失敗",
	AjaxMsg17 : "刪除分享錯誤，Ajax Error:"
}