var LanguageStr_VM =
{
    VM_Delete : "您現在要刪除@嗎?",
    VM_Export : "&之相關檔案將會匯出，並且放在\"本機之Samba的EXPORT目錄\"上。\r\n\r\n您現在要匯出@嗎?",
    VM_Import_Ask : "您現在要匯入@嗎?",
    VM_Str_Import : "匯入",
    VM_Delete_VD_First : '請先刪除 & 所有的用戶桌面，然後再刪除此桌面',
    VM_Delete_Shutdown_First : '請先關機或強制關機 & ，然後再刪除',
    VM_Disable_Shutdown_First : '請先關機或強制關機 & ，然後再停用',
    VM_Poweron_ask : '您現在要開機@嗎?',
    VM_Shutdown_ask : '您現在要關機@嗎?',
    VM_Poweroff_ask : '您現在要強制關機@嗎?',
    VM_Enable_ask : '您現在要啟用@嗎?',
    VM_Disable_ask : '您現在要停用@嗎?',
    VM_ResetPWD_ask : "您現在要重置@的" + '密碼為"000000"?',
    VM_Destination_Warning : "請在目的端名稱欄位輸入值",
    VM_Clone_Name_Warning : '您只能在名稱(&)欄位輸入 "A-Z 0-9 a-z _"',
    VM_Clone_Name_Warning_1 : "您不能在名稱(&)欄位輸入數字",
    VM_Clone_Name_Warning_2 : "名稱(&)重複，請您重新輸入",
    VM_Name_Duplicate : "建立失敗(名稱重複)",
    VM_Name_Empty_Warning : "請在名稱欄位輸入值",
    VM_Memory_Integer_Warning : '請在記憶體欄位輸入整數或整數與2位小數',
    VM_NewDisk_Integer_Warning : '請在新建磁碟欄位輸入整數',
    VM_Create_Fail : '建立@失敗',
    VM_Import_Fail : '匯入@失敗',
    VM_Export_Fail : '匯出@(&)失敗，請檢查RAID的容量是否足夠!',
    VM_Export_Success : "@之相關檔案匯出成功！\r\n\r\n請用PC連到該VDI儲存伺服器(IP:&)之Samba，用\"manger\"帳號登入，將\"manager/EXPORT目錄\"內之相關資料複製即可。",
    VM_Import_No_VD : '沒有@可匯入',
    VM_Clone : '克隆@',
    VM_Make_Seed : '建立種子',
    VM_Delete_Borned_Warning : "請先刪除 & 的所有@",
    VM_Delete_Seed_ask : "您現在要刪除 Seed 嗎?",
    VM_Delete_NIC_ask : "您要刪除這個網路設定嗎?",
    VM_Delete_Txt : "刪除",
    VM_Boot_Disk : "開機磁碟 :",
    VM_Data_Disk : "資料磁碟 :",
    VM_Setting : "設定",
    VM_Task_Clone : "克隆",
    VM_Task_Make_Seed : "建立種子",
    VM_Task_Create_Original : '建立原生桌面',
    VM_Born_Users : "產生用戶",
    VM_Task_Add_Disk : "新增磁碟",
    VM_Task_Del_Disk : "刪除磁碟",
    VM_Task_Export_VD : "匯出桌面",
    VM_Task_Import_VD : "匯入桌面",
    VM_Task_Failed : "失敗",
    VM_Task_Completed : "完成",
    VM_Task_Waiting : "等待中",
    VM_Task_Cloning : "處理中",
    VM_Enable : "啟用",
    VM_Disable : "停用",
    VM_Stop : "停止",
    VM_Waiting_Poweron : "等待開機",
    VM_Poweron : "開機",
    VM_Blocked : "鎖定",
    VM_Pause : "暫停",
    VM_Shutdowning : "關機中",
    VM_Shutdown : "關機",
    VM_Crash : "損壞",
    VM_Suspend : "暫停",
    VM_Disconnected : "離線",
    VM_Connected : "連線",    
    VM_Modify_Name_Fail : "修改桌面失敗",
    VM_Modify : "修改",
    VM_Seed : "種子",
    VM_Information : "資訊",
    VM_Create_Original : '建立"原生"',
    VM_Import_Original : '匯入"原生"',
    VM_Limited : '限制',
    VM_UnLimited : '無限制',
    /* SnapShot 2017.02.06 william */ 
    VM_Snapshot : '快照',
    VM_SSIsview_ON : '是', 
    VM_SSIsview_OFF : '否',
    VM_SnapshotType_take : '產生快照',
    VM_SnapshotType_delete : '刪除快照',
    VM_SnapshotType_rollback : '還原快照',
    VM_SnapshotType_view : '檢視快照',
    VM_SnapshotType_view_stop : '關閉檢視',
    VM_SnapshotType_Schedule_Take: '排程快照',

    VM_SnapshotState_Normal : '待命',
    VM_SnapshotState_Preparing_view : '檢視中',
    VM_SnapshotState_View : '檢視',
    VM_SnapshotState_Preparing_delete : '刪除中',
    VM_SnapshotState_Preparing_rollback : '還原中',
    VM_SnapshotState_Preparing_unview : '關閉檢視中'   
}

