var LanguageStr_Error =
{
    Error_DB : '错误 : 数据库服务无法使用。',
    Error_Authorization : '错误 : 认证失败。',
    Error_PWD_Modify : '错误 : 密码修改失败。',
    Error_Time_Set : '错误 : 时间设定失败。',
    Error_Time_Update : '错误 : 时间更新失败。',
    Error_Get_IP : "错误 : 取得 IP 失败，因为与服务器联机失败。",
    Error_Set_IP : "错误 : 设定 IP 失败，因为与服务器联机失败。",
    Error_List_Version : "错误 : 取得版本失败，因为与服务器联机失败。",
    Error_Check_Version : "错误 : 检查新版本失败，因为与服务器联机失败。",
    Error_Check_Update : "错误 : 更新检查失败，因为与服务器联机失败。",
    Error_List_log : "错误 : 取得日志失败，因为与服务器联机失败。",
    Error_List_Time : "错误 : 取得时间失败，因为与服务器联机失败。",
    Error_Set_Time : "错误 : 设定时间失败，因为与服务器联机失败。",
    Error_List_SMB : "错误 : 取得 Samba 服务状态失败，因为与服务器联机失败。",
    Error_Set_SMB : "错误 : 设定 Samba 服务状态失败，因为与服务器联机失败。",
    Error_List_SSH : "错误 : 取得 SSH 服务状态失败，因为与服务器联机失败。",
    Error_Set_SSH : "错误 : 设定 SSH 服务状态失败，因为与服务器联机失败。",
    Error_VM_Status : "错误 : 取得 @ 状态失败，因为与服务器联机失败。",
    Error_List_VM : "错误 : 取得 @ 列表失败，因为与服务器联机失败。",
    Error_VM_Shutdown : "错误 : @ 关机失败，因为与服务器联机失败。",
    Error_VM_Poweroff : "错误 : @ 强制关机失败，因为与服务器联机失败。",
    Error_VM_Poweron : "错误 : @ 开机失败，因为与服务器联机失败。",
    Error_VM_Delete : "错误 : @ 删除失败，因为与服务器联机失败。",
    Error_VM_List_Img : "错误 : Failed to List existing disk since conneciton timeout.",
    Error_VM_Create : "错误 : 建立 @ 失败，因为与服务器联机失败。",
    Error_VM_List_Info : "错误 : 取得 @ 信息失败，因为与服务器联机失败。",
    Error_VM_Delete_Disk : "错误 : 删除 @ 磁盘失败，因为与服务器联机失败。",
    Error_VM_Modify_Properties : "错误 : 修改 @ 属性失败，因为与服务器联机失败。",
    Error_VM_ResetPWD : "错误 : 重置 @ 的密码失败，因为与服务器联机失败。",
    Error_VM_Enable : "错误 : 启用 @ 失败，因为与服务器联机失败。",
    Error_VM_Disable : "错误 : 停用 @ 失败，因为与服务器联机失败。",
    Error_VM_List_Task :"错误 : 取得 @ 任务列表失败，因为与服务器联机失败。",
    Error_VM_Suspend :"错误 : 暂停 @ 失败，因为与服务器联机失败。",
    Error_VM_Clone : "错误 : 克隆 @ 失败，因为与服务器联机失败。",
    Error_VM_Delete_Task : "错误 : 删除 @ 任务列表失败，因为与服务器联机失败。",
    Error_SMB_Change_PWD : "错误 : 修改密码失败，因为与服务器联机失败。",
    Error_iSCSI_Discovery : "错误 : iSCSI 探索失败，因为与服务器联机失败。",
    Error_iSCSI_Login : "错误 : iSCSI 登入失败，因为与服务器联机失败。",
    Error_iSCSI_List : "错误 : 取得 iSCSI 列表失败，因为与服务器联机失败。",
    Error_iSCSI_Logout : "错误 : iSCSI 注销失败，因为与服务器联机失败。",
    Error_List_Disk : "错误 : 取得磁盘列表失败，因为与服务器联机失败。",
    Error_Reset_Disk : "错误 :  重置磁盘失败，因为与服务器联机失败。",
    Error_Delete_RAID : "错误 : 删除 RAID 失败，因为与服务器联机失败。",
    Error_Create_RAID : "错误 : 建立 RAID 失败，因为与服务器联机失败。",
    Error_Recovery_RAID : "错误 :复原 RAID 失败，因为与服务器联机失败。",
    Error_List_Hostname : "错误 :取得主机名失败，因为与服务器联机失败。",
    Error_Set_Hostname : "错误 : 设定主机名失败，因为与服务器联机失败。",
    Error_List_ExternalIP : "错误 : 取得外部 IP 失败，因为与服务器联机失败。",
    Error_Set_ExternalIP : "错误 : 设定外部 IP 失败，因为与服务器联机失败。",    
    Error_List_Alarm : "错误 : 取得蜂鸣器状态失败，因为与服务器联机失败。",
    Error_Set_Alarm : "错误 : 设定蜂鸣器状态失败，因为与服务器联机失败。",
    Error_VM_Export : "错误 : 汇出 @ 失败，因为与服务器联机失败。",
    Error_VM_Import : "错误 : 汇入 @ 失败，因为与服务器联机失败。",
    Error_VM_List_Import : "错误 : 列出可汇入 @ 失败，因为与服务器联机失败。",
    Error_List_AD : "错误 : 取得 AD 失败，因为与服务器联机失败。",
    Error_Set_AD : "错误 : 设定 AD 失败，因为与服务器联机失败。",
    Error_List_UPS : "错误 : 取得 UPS 失败，因为与服务器联机失败。",
    Error_Set_UPS : "错误 : 设定 UPS 失败，因为与服务器联机失败。"    
}