var LanguageStr_Service =
{
    Service_New_Password_Empty : "密码栏不能为空白",
    Service_Confirm_Password_Empty : "确认密码栏不能为空白",
    Service_Password_Whitespace : "密码不能输入空格符",
    Service_Password_Not_Same : "密码与确认密码栏输入的值必须相同",
    /* SnapShot&Schedule&Backup  2017.01.11 william */   
    Service_SS_Schedule_title : "排程快照之排程设定",
    Service_SS_Schedule_title2 : "排程快照之快照目标设定",    
    Service_Schedule_DeleteAsk : "您确定要删除快照排程吗?",
    Service_Schedule_JobsAsk : "警告：只能选择『一个』任务，不能多选!",
    Service_Schedule_RuleAsk : "警告：只能选择『一个』排程，不能多选!",                     

    Service_BK_Schedule_title : "排程备份之排程设定",
    Service_BK_Schedule_title2 : "排程备份之备份目标设定",

    Service_CheckBackupState0 : "未初始化",
    Service_CheckBackupState1 : "未初始化",
    Service_CheckBackupState2 : "备份版本不同，初始化才能使用",
    Service_CheckBackupState3 : "此iSCSI LUN已经被其他超融合主机使用过，请问是否采用?",
    Service_CheckBackupState4 : "",        
    Service_CheckBackupState5 : "未初始化",
    Service_BackupDesc_Empty_Warning : "请在描述字段输入值",
    Service_BackupAsk : "您确定要备份吗?",
    Service_RestoreAsk : "您确定要复原吗?",
    Service_BackupVDDeleteAsk : "您确定要删除备份端VD吗?",
    VM_BackupType_backup : "备份",
    VM_BackupType_restorenew : "建立新还原",
    VM_BackupType_restoresame : "还原覆盖",    
    VM_BackupType_schedulebackup : "排程备份",
    BackupVD_Rename : "VD名称重复，请重新命名",
    Service_LUN_Connection : "存储连线设定",
    BackupMgt_Message1 : "尚未备份",
    BackupMgt_Message2 : "尚未还原",
    Backup_FormatAsk : "您确定初始化吗?",
    CheckBackupLUN_failure : "连线失败",
    BackupLUN_disconnect : "关闭连线",
    BackupLUN_OnlineCheck : "已连线",
    BackupLUN_OfflineCheck : "已断线",
    Timepicker_btntext_currentText : "现在",
    Timepicker_btntext_closeText : "完成",
    BackupLUN_OfflineMessage_Warning : "警告 !",
    BackupMgt_Bktitle : "备份端",
    Backup_ClearAllAsk : "您确定清空备份吗?",
    Backup_ClearAllComplete : "清空备份完成",
    Backup_SourceVD_Crash : "VD毁损，无法备份",
    Backup_BKVD_Fail : "备份失败，请重新备份",
    BackupMgt_AllBK_Capacity : "备份端容量 : ",
    BackupMgt_Total_Capacity : "总容量 : ",
    BackupMgt_Avail_Capacity : "可用容量 : ",
    BackupMgt_Used_Capacity : "已使用容量 : ",
    BackupMgt_BK_Capacity : "备份档案 : ",
    BackupMgt_FS_Capacity : "系统档案 : ",
    BackupMgt_text_Dot : "。",
    Schedule_Create_Fail : "1. 检查名称是否为空白或是重复!\n2. 检查排程类型及开始日期是否为空白!",
    SelectRAID : "选择RAID"
}