var LanguageStr_VM =
{
    VM_Delete : "您现在要删除@吗?",    
    VM_Export : "&之相关档案将会汇出，并且放在\"本机之Samba的EXPORT目录\"上。\r\n\r\n您现在要汇出@吗?",
    VM_Import_Ask : "您现在要汇入@吗?",
    VM_Str_Import : "汇入",
    VM_Delete_VD_First : '请先删除 & 所有的云桌面，然后再删除此桌面',
    VM_Delete_Shutdown_First : '请先关机或强制关机 & ，然后再删除',
    VM_Disable_Shutdown_First : '请先关机或强制关机 & ，然后再停用',
    VM_Poweron_ask : '您现在要开机@吗?',
    VM_Shutdown_ask : '您现在要关机@吗?',
    VM_Poweroff_ask : '您现在要强制关机@吗?',
    VM_Enable_ask : '您现在要启用@吗?',
    VM_Disable_ask : '您现在要停用@吗?',
    VM_ResetPWD_ask : "您现在要重置@的" + '密码为"000000"?',
    VM_Destination_Warning : "请在目的端名称字段输入值",
    VM_Clone_Name_Warning : '您只能在VD名称(&)字段输入 "A-Z 0-9 a-z _"',
    VM_Clone_Name_Warning_1 : "您不能在VD名称(&)字段输入数字",
    VM_Clone_Name_Warning_2 : "VD名称(&)重复，请您重新输入",
    VM_Name_Duplicate : "建立失败(VD名称重复)",
    VM_Name_Empty_Warning : "请在VD名称字段输入值",
    VM_Memory_Integer_Warning : '请在内存字段输入整数或整数与2位小数',
    VM_NewDisk_Integer_Warning : '请在新建磁盘字段输入整数',
    VM_Create_Fail : '建立@失败',
    VM_Import_Fail : '汇入@失败',
    VM_Export_Fail : '汇出@(&)失败',
    VM_Export_Success : "@之相关档案汇出成功！\r\n\r\n请用PC连到该VDI储存服务器(IP:&)之Samba，用\"manger\"账号登入，将\"manager/EXPORT目录\"内之相关数据复制即可。",
    VM_Import_No_VD : '没有@可汇入',
    VM_Clone : '克隆@',
    VM_Clone_UserVD : '克隆@',    
    VM_Clone_UserVD_Failure : '克隆@失败',
    VM_Make_Seed : '建立种子',
    VM_Delete_Borned_Warning : "请先删除 & 的所有@",
    VM_Delete_Seed_ask : "您现在要删除種子 VD 吗?",
    VM_Delete_NIC_ask : "您要删除这个网络设定吗?",
    VM_Delete_Txt : "删除",
    VM_Boot_Disk : "开机磁盘 :",
    VM_Data_Disk : "数据磁盘 :",
    VM_Setting : "設定",
    VM_Task_Clone : "克隆",
    VM_Task_Make_Seed : "建立种子",
    VM_Task_Create_Original : '建立云主机',
    VM_Born_Users : "产生云",
    VM_Task_Add_Disk : "新增磁盘",
    VM_Task_Del_Disk : "删除磁盘",
    VM_Task_Export_VD : "汇出桌面",
    VM_Task_Import_VD : "汇入桌面",
    VM_Task_Overwrite_Seed : "覆写种子",
    VM_Task_Reborn_User : "重布云桌面",
    VM_Task_Renew_User : "更新生成云桌面",
    VM_Task_Recovery_User : "复原云桌面",
    VM_Task_Clone_to_Org : "克隆至云主机",
    VM_Task_Failed : "失败",
    VM_Task_Completed : "完成",
    VM_Task_Waiting : "等待中",
    VM_Task_Cloning : "处理中",    
    VM_Enable : "启用",
    VM_Disable : "停用",
    VM_Stop : "停止",
    VM_Waiting_Poweron : "等待开机",
    VM_Poweron : "开机",
    VM_Blocked : "锁定",
    VM_Pause : "暂停",
    VM_Shutdowning : "关机中",
    VM_Shutdown : "关机",
    VM_Crash : "损坏",
    VM_Suspend : "暂停",
    VM_Disconnected : "脱机",
    VM_Connected : "联机",    
    VM_Modify_Name_Fail : "修改桌面失败",
    VM_Modify : "修改",
    VM_Seed : "种子",
    VM_Information : "信息",
    VM_Create_Original : '建立"云主机"',
    VM_Import_Original : '汇入"云主机"',
    VM_Limited : '限制',
    VM_UnLimited : '无限制',
    /* SnapShot 2017.02.06 william */     
    VM_Snapshot : '快照',
    VM_SSIsview_ON : '是', 
    VM_SSIsview_OFF : '否',
    VM_SnapshotType_take : '产生快照',
    VM_SnapshotType_delete : '删除快照',
    VM_SnapshotType_rollback : '还原快照',
    VM_SnapshotType_view : '检视快照',
    VM_SnapshotType_view_stop : '关闭检视',
    VM_SnapshotType_Schedule_Take: '排程快照',

    VM_SnapshotState_Normal : '待命',
    VM_SnapshotState_Preparing_view : '检视中',
    VM_SnapshotState_View : '检视',
    VM_SnapshotState_Preparing_delete : '删除中',
    VM_SnapshotState_Preparing_rollback : '还原中',
    VM_SnapshotState_Preparing_unview : '关闭检视中',
    // 新增CPU類型  2017.09.01 william
    VM_CPUType_fullvirtual : '虚拟CPU',
    VM_CPUType_Halfvirtual : '实体CPU',
    VM_SnapShotLayer_Empty_Warning : "请在快照层数字段输入数字",
    VM_SnapShotLayer_Error1:"快照层数不能低于30",
    VM_SnapShotLayer_Error2:"快照层数不能超过1000",
    VM_SnapShotLayer_Recommendation:"快照层数建议不要超过500层",   
    /* 2018.01.08 william 新增磁碟擴充功能，建立擴充視窗 */ 
    VM_Expend_Disk_Txt : "扩充", 
    VM_ExpendDisk_title : "扩充磁碟",    
    VM_Disktype_warning : "相同磁碟类型不能超过2个，请选择其他磁碟类型",
    VM_UserList_title : "用户列表",
    VM_SeedList_title : "种子列表",
    Expand_Disk : "扩充磁碟",
    Move_Disk : "搬移磁碟",
    Move_User_Profile : "搬移用户Profile",
    Move : "搬移",        
    Moving : "搬移中",
    User_Name_Warning : '您只能在用户名称(&)字段输入 "A-Z 0-9 a-z _"',
    User_Name_Warning_1 : "您不能在用户名称(&)字段输入数字",
    User_Name_Warning_2 : "用户名称(&)重复，请您重新输入",
    User_Name_Duplicate : "建立失败(用户名称重复)",
    User_Name_Empty_Warning : "请在用户名称字段输入值",    
    Virtual_Host_Name_Str : "云主机名称 :"    
}