var LanguageStr_SharePeriod =
{
	Input_RadioPeriodMode_DateSelect : "请务必选择日期",
	H4_DescriptionPeriod : "已经过期",
	WDay0 : "星期日",
	WDay1 : "星期一",
	WDay2 : "星期二",
	WDay3 : "星期三",
	WDay4 : "星期四",
	WDay5 : "星期五",
	WDay6 : "星期六",
	WD0 : "日",
	WD1 : "一",
	WD2 : "二",
	WD3 : "三",
	WD4 : "四",
	WD5 : "五",
	WD6 : "六",
	Month01 : "一月",
	Month02 : "二月",
	Month03 : "三月",
	Month04 : "四月",
	Month05 : "五月",
	Month06 : "六月",
	Month07 : "七月",
	Month08 : "八月",
	Month09 : "九月",
	Month10 : "十月",
	Month11 : "十一月",
	Month12 : "十二月",
	PreviosMonth : "上月",
	NextMonth : "次月",
        SelectTime : "选择时分秒",
        Time : "时间",
	WeekHeader : "周",
	Hour : "时",
	Minute : "分",
	Second : "秒",
        MilliSecond : "毫秒",
        TimeZone : "时区",
        AM : "上午",
        PM : "下午",
	NowTime : "现在时间",
	OK : "确定",
	
	
	AjaxMsg00 : "设定分享期间成功",
	AjaxMsg01 : "设定分享期间错误，参数错误",
	AjaxMsg02 : "设定分享期间错误，Access Key 错误",
	AjaxMsg03 : "设定分享期间错误，数据库错误",
	AjaxMsg04 : "您没有变更分享期间",
	AjaxMsg05 : "无法设定今天之前的日期（无效设定）",
	AjaxMsg06 : "设定分享期间错误，修改内容错误",
	AjaxMsg07 : "设定分享期间错误 未知的原因，代码为：",
	AjaxMsg08 : "删除分享错误，Ajax Error:",
	
	AjaxMsg10 : "删除账号分享错误，参数错误",
	AjaxMsg11 : "删除账号分享错误，Access Key 错误",
	AjaxMsg12 : "删除账号分享错误，数据库错误",
	AjaxMsg13 : "删除账号分享错误，建立错误",
	AjaxMsg14 : "删除账号分享错误，未知的原因，代码为：",
	AjaxMsg15 : "删除成功",
	AjaxMsg16 : "删除失败",
	AjaxMsg17 : "删除分享错误，Ajax Error:"
}