var LanguageStr_Account =
{
	DialogTitleCreaete: "建立使用者",
	DialogTitleEdit: "編輯使用者",
	NoData: "無",
	ImgEdit: "編輯",
	ImgDelete: "刪除",
	NoUserAtList: "目前沒有建立任何使用者帳號",
	CreateUserMsg01: "帳號不得為空白",
	CreateUserMsg02: "配置空間不得為空白或小於1G",
	CreateUserMsg03: "配置空間必須是數字",
	CreateUserMsg04: "Email不得為空白",
	CreateUserMsg05: "名不得為空白",
	CreateUserMsg06: "姓不得為空白",
	CreateUserMsg07: "公司數值錯誤",
	CreateUserMsg08: "部門數值錯誤",
	CreateUserMsg09: "子部門數值錯誤",
	CreateUserMsg10: "權限數值錯誤",
	
	Ajax00: "查詢失敗！ 資料傳輸錯誤，請確認網路穩定性。 (User)",
	Ajax01: "目前無法顯示任何使用者帳號",
	Ajax02: "建立RAID之前，使用者功能無法使用",
	Ajax03: "取得使用者清單失敗",
	Ajax04: "建立使用者失敗，錯誤代碼為：",
	Ajax05: "建立使用成功",
	Ajax06: "建立使用者失敗，資料傳輸錯誤，請確認網路穩定性。 (User)",
	Ajax07: "編輯使用者失敗，錯誤代碼為：",
	Ajax08: "編輯使用者失敗，資料傳輸錯誤，請確認網路穩定性。 (User)",
	Ajax09: "刪除使用者失敗，錯誤代碼為：",
	Ajax10: "建立使用者失敗，資料傳輸錯誤，請確認網路穩定性。 (User)"
}