var LanguageStr_Error =
{
    Error_DB : 'Error : DB service is unavaliable.',
    Error_Authorization : 'Error : Authorization Error.',
    Error_PWD_Modify : 'Error : Password is modified faliure.',
    Error_Time_Set : 'Error : Time is setted faliure.',
    Error_Time_Update : 'Error : Time is updatted faliure.',
    Error_Get_IP : "Error : Failed to Get IP since conneciton timeout.",
    Error_Set_IP : "Error : Failed to Set IP since conneciton timeout.",
    Error_List_Version : "Error : Failed to List Version since conneciton timeout.",
    Error_Check_Version : "Error : Failed to Check New Version since conneciton timeout.",
    Error_Check_Update : "Error : Failed to Check Update since conneciton timeout.",
    Error_List_log : "Error : Failed to List Log since conneciton timeout.",
    Error_List_Time : "Error : Failed to List Time since conneciton timeout.",
    Error_Set_Time : "Error : Failed to Set Time since conneciton timeout.",
    Error_List_SMB : "Error : Failed to List SMB since conneciton timeout.",
    Error_Set_SMB : "Error : Failed to Set SMB since conneciton timeout.",
    Error_List_SSH : "Error : Failed to List SSH since conneciton timeout.",
    Error_Set_SSH : "Error : Failed to Set SSH since conneciton timeout.",
    Error_VM_Status : "Error : Failed to Get @ Stauts since conneciton timeout.",
    Error_List_VM : "Error : Failed to List @ since conneciton timeout.",
    Error_VM_Shutdown : "Error : Failed to Shutdown @ since conneciton timeout.",
    Error_VM_Poweroff : "Error : Failed to Poweroff @ since conneciton timeout.",
    Error_VM_Poweron : "Error : Failed to Poweron @ since conneciton timeout.",
    Error_VM_Delete : "Error : Failed to Delete @ since conneciton timeout.",
    Error_VM_List_Img : "Error : Failed to List existing disk since conneciton timeout.",
    Error_VM_Create : "Error : Failed to Create @ since conneciton timeout.",
    Error_VM_List_Info : "Error : Failed to List @ Info since conneciton timeout.",
    Error_VM_Delete_Disk : "Error : Failed to Delete @ Disk since conneciton timeout.",
    Error_VM_Modify_Properties : "Error : Failed to Modify @ Properties since conneciton timeout.",
    Error_VM_ResetPWD : "Error : Failed to Reset @'s Password since conneciton timeout.",
    Error_VM_Enable : "Error : Failed to Enable @ since conneciton timeout.",
    Error_VM_Disable : "Error : Failed to Disable @ since conneciton timeout.",
    Error_VM_List_Task :"Error : Failed to List @ Task since conneciton timeout.",
    Error_VM_Suspend :"Error : Failed to Suspend @ since conneciton timeout.",
    Error_VM_Clone : "Error : Failed to Clone @ since conneciton timeout.",
    Error_VM_Delete_Task : "Error : Failed to Delete @ Tasks since conneciton timeout.",
    Error_SMB_Change_PWD : "Error : Failed to Change Password since conneciton timeout.",
    Error_iSCSI_Discovery : "Error : Failed to Discovery since conneciton timeout.",
    Error_iSCSI_Login : "Error : Failed to Login since conneciton timeout.",
    Error_iSCSI_List : "Error : Failed to List iSCSI since conneciton timeout.",
    Error_iSCSI_Logout : "Error : Failed to Logout since conneciton timeout.",
    Error_List_Disk : "Error : Failed to List Disk since conneciton timeout.",
    Error_Reset_Disk : "Error : Failed to Reset Disk since conneciton timeout.",
    Error_Delete_RAID : "Error : Failed to Delete RAID since conneciton timeout.",
    Error_Create_RAID : "Error : Failed to Create RAID since conneciton timeout.",
    Error_Recovery_RAID : "Error : Failed to Recovery RAID since conneciton timeout.",
    Error_List_Hostname : "Error : Failed to List Hostname since conneciton timeout.",
    Error_Set_Hostname : "Error : Failed to Set Hostname since conneciton timeout.",
    Error_List_ExternalIP : "Error : Failed to List External IP since conneciton timeout.",
    Error_Set_ExternalIP : "Error : Failed to Set External IP since conneciton timeout.",
    Error_List_Alarm : "Error : Failed to List Alarm status since conneciton timeout.",
    Error_Set_Alarm : "Error : Failed to Set Alarm status since conneciton timeout.",
    Error_VM_Export : "Error : Failed to Export @ since conneciton timeout.",
    Error_VM_Import : "Error : Failed to Import @ since conneciton timeout.",
    Error_VM_List_Import : "Error : Failed to List Importable @ since conneciton timeout."
}

